title: codeklasse
email: sergej@codeklasse.de
description: Programmieren lernen für Kinder - mit Emojis! codeklasse ermöglicht altersgerechtes, frustfreies Programmieren lernen ohne Bedarf von Lesekompetenz oder Vorkenntnissen.  
baseurl: "/" # the subpath of your site, e.g. /blog
url: "/" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /blog/:title/

contact_phone: 0162 3292 122 
contact_mail: sergej@codeklasse.de

plugins:
  - jekyll-feed


exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock, vendor, portfolio-assets/portfolio-photos/.git/FETCH_HEAD]

sass:
    sass_dir: _sass

collections:
  faq:
    output: true 