baseURL = "https://codeklasse.de/"
title = "codeklasse"

tags = []
features = []

[author]
  name = "Sergej Grilborzer"
  homepage = "https://grilborzer.de"

[params]
  favicon = ''
  facebook = ''
  twitter = 'https://twitter.com/GoHugoIO'
  instagram = ''
  youtube = ''
  github = ''
  linkedin = ''