baseURL = "https://codeklasse.de/"
title = "codeklasse"

tags = []
features = []

[markup.goldmark.renderer]
  unsafe= true

[author]
  name = "Sergej Grilborzer"
  homepage = "https://grilborzer.de"

[params]
  facebook = ''
  twitter = 'https://twitter.com/GoHugoIO'
  instagram = ''
  youtube = ''
  github = ''
  linkedin = ''